version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3306:3306"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Porta 3307 no host será mapeada para a porta padrão (3306) do container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
